# Generated by Django 3.2.8 on 2021-11-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=None, unique=True)),
                ('base_url', models.URLField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, unique=True)),
                ('fields', models.JSONField()),
                ('formula', models.CharField(max_length=20)),
                ('url_query_suffix', models.CharField(max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='similarity.datasources', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntitiesConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_entity_a', models.CharField(max_length=20)),
                ('field_entity_b', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=20)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='related_to', to='similarity.entitytypes')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='similarity.entitytypes')),
            ],
        ),
    ]
